### ISSUE TITLE
getElementById を使わないようにする

### ISSUE THREAD

**Issue by itok01** [girakdev/Girack#17]
https://github.com/NfoAlex/Girack/blob/e2e62e8af7c47e90160304c3e6b00199ee5ca312/components/chatW.js#L60
https://github.com/NfoAlex/Girack/blob/e2e62e8af7c47e90160304c3e6b00199ee5ca312/components/chatW.js#L103
https://github.com/NfoAlex/Girack/blob/e2e62e8af7c47e90160304c3e6b00199ee5ca312/components/chatW.js#L107
https://github.com/NfoAlex/Girack/blob/e2e62e8af7c47e90160304c3e6b00199ee5ca312/components/chatW.js#L112

**Comment by ayok01** [comment]
頑張れ
