### ISSUE TITLE
home画面にウィジェットを追加したい

### ISSUE THREAD

**Issue by ayok01** [girakdev/Girack#22]
具体的なUIを作ってみるわ

**Comment by NfoAlex** [comment]
JSXストア的なやつやろうぜ
ポータル？の下らへんにボタン作って

**Comment by ayok01** [comment]
どゆこと

**Comment by ayok01** [comment]
![image](https://user-images.githubusercontent.com/39289591/94225887-22c46c80-ff31-11ea-9aa5-5a937507b396.png)

**Comment by ayok01** [comment]
こういうのどうよ

**Comment by ayok01** [comment]
作成した
