### ISSUE TITLE
 Prop `className` did not match.

### ISSUE THREAD

**Issue by ayok01** [girakdev/Girack#28]
![image](https://user-images.githubusercontent.com/39289591/93707678-b120a300-fb6b-11ea-9e0b-287acc1e132b.png)

**Comment by ayok01** [comment]
リンクに飛ぶと直る

**Comment by ayok01** [comment]
最初アクセスするとやっぱり崩れる

**Comment by NfoAlex** [comment]
これは初めてみたんだけど再現法とかわかったりしない？

**Comment by ayok01** [comment]
あとで調べてみる

**Comment by ayok01** [comment]
https://github.com/girakdev/Girack/blob/master/styles/useStyles.ts
が適応されてないときがある

**Comment by NfoAlex** [comment]
知らんがな

**Comment by ayok01** [comment]
わかったんだよ

**Comment by ayok01** [comment]
urlにアンカーリンクがついてるとレイアウトバグは起きなかった
ただurlだけでリロードするとレイアウトバグが起きる

**Comment by ayok01** [comment]
あ、でもこれアンカーリンクがついててもリロードするとレイアウトバグおきます。

**Comment by ayok01** [comment]
# **なにもしてないのに直った**

**Comment by ayok01** [comment]
# 直ってないんだけど

**Comment by ayok01** [comment]
yarn buildしたら直るんだけど
@NfoAlex 
@itok01

**Comment by ayok01** [comment]
Fixed.
