### ISSUE TITLE
全画面時チャットバーとチャットウィンドウの間に空白が発生する

### ISSUE THREAD

**Issue by ayok01** [girakdev/Girack#5]
![image](https://user-images.githubusercontent.com/39289591/93671587-2e520680-fadf-11ea-87d8-1afe16033fcd.png)

**Comment by ayok01** [comment]
https://github.com/girakdev/Girack/blob/e73f5ef32e7e216e4b7de0763cc6a518cee140a6/styles/useStyles.ts#L8
を消せば一応直るけどチャットバーが横に大きくなる

**Comment by NfoAlex** [comment]
その部分をJSで実装してほしいわ

**Comment by NfoAlex** [comment]
それか[MaterialUI](https://material-ui.com/)で実装して幅とかを調節できるようにしたらええんちゃう

**Comment by ayok01** [comment]
調べてみるわ

**Comment by ayok01** [comment]
https://github.com/girakdev/Girack/tree/kirota401e/change_chatber
でチャットーバーを変えたときに直しました
